databases:
  - name: blog_app
    databaseName: blog_app
    user: blog_app

services:
  - type: web
    name: blog_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_app
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
        